    language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build 
after_script:
  - cd ./dist
  - git init
  - git config user.name "caihai123"
  - git config user.email "1027747358@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - gh-page
env:
 global:
   - GH_REF: git@github.com:caihai123/caihai123.github.io.git